# Generated by Django 5.1 on 2024-08-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tumorprediction',
            name='image_path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
